project:
  type: website
  output-dir: docs

website:
  title: "QUEST at Bates College"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: Home
      - sidebar:starthere
      - sidebar:thesis
      - sidebar:computing
      #- sidebar:projects
  
  sidebar:
    - id: starthere
      title: "Start Here"
      style: "docked"
      background: light
      contents:
       - starthere.qmd
       - manual.qmd
       
    - id: thesis
      title: "Thesis at Bates"
      style: "docked"
      background: light
      contents:
       - thesis.qmd
       - href: https://www.bates.edu/honors/calendar/
         text: "Honors Thesis Calendar" 
         target: _blank #makes it open in new page
         
    - id: computing
      title: "Computing at Bates"
      style: "docked"
      background: light
      contents:
        - leavittonboarding.qmd
        - metisonboarding.qmd
        - href: https://www.bates.edu/research-resources/etna/
          text: "Etna: Data Storage at Bates"
          target: _blank

    #- id: projects
    #  title: "Projects"
    #  style: "docked"
    #  background: light
    #  contents:
    #    - PeakMap.qmd
    #    - NonLinearSigma.qmd
    

   
   
format:
  html:
    theme: bates_yeti.scss
    toc: true


