---
title: "QUEST group lab manual"
format: 
  html:
    link-external-newwindow: true
editor: source
---

# Group Philosophy

- Research can be enjoyable, productive, and exciting. It can also be intimidating, overwhelming, and tedious. Both can coexist, and learning what you want to have more of and what you are willing to live with (and what you are not) is helpful in developing your own research philosophy and direction.
- Making mistakes is part of the process. You shouldn’t be embarrassed or ashamed about mistakes, as they are an amazing opportunity to learn (and failure is a far more effective teacher than success).
- We do real research in this group, and you are real scientists.
- All of us, no matter how many years we have been doing this, have a lot to learn from each other.
- Research does not have a syllabus or an answer key, so you have to learn to set your own goals, assess your own progress, and motivate yourself to put in the hard work, stay positive when it gets challenging, and ask for help when you need it. I will be here to help you with that along the way, but you have to put in the work to get started.

# Expectations

## From Casey

- I will communicate my expectations to you clearly and respond to emails and questions in a timely fashion.
- I may not have time for everything, and when I don’t, I will be transparent about my abilities and my limitations.
- I will do my very best to meet you where you are and help you find work that interests you and develop the skills you need and want for your career goals, whether or not those involve research.

## From you

- I expect you to put in consistent work on the research.
- I expect you to log your time if you are doing research for credit (thesis) or if you are doing paid hourly work.
- I expect you to communicate in a clear and timely fashion. Please respond to emails within 48 hours, especially those which contain a deadline in them.
- I expect you to treat your fellow students with respect and compassion.
- I expect you to attend all group meetings if you are enrolled in research for credit (senior thesis) or if you are doing paid hourly work (you should log research meetings as work time)

# What does research work look like in this group?

It can look like a lot of things! Mostly, it looks like writing code, running code, and analyzing data.  Right now, the only work available in this group is for senior thesis, though I hope to eventually have summer and semester paid work available.

## General information and policies (for all research positions)

### Weekly group meetings and presentations

We will meet once a week during the term for a period of one hour. Each week, you should be prepared to present 3 slides (~5 minutes of time) on your work over the past week. Your three slides should be:

1. Progress made on your goals for the week
2. What worked/what didn’t (it’s okay to be stuck!)
3. Your goals for next week

At least one hour prior to our group meeting, I expect you to post your slides in the current semester channel in the group slack workspace.

Presenting on your work can be intimidating, but it’s a very normal part of the research process to discuss work that is completed or still in-progress. This weekly practice should make it easier to do your mid-semester progress report to the department as well as your final thesis presentation, as you will already have practiced preparing slides and discussing your work.

Once everyone has presented their update for the week, we will have open time to work together on problem solving, if that is useful, or for me to answer individual questions.

If you need more time to discuss something with me, or if you get stuck mid-week and need to talk, you can use this [calendly link](https://calendly.com/caseyberger/research-meeting) to set a 30 minute meeting with me.

### Slack use policy

The most important rule of using the group’s slack workspace is that you will be professional, respectful, and kind to your peers. 

In addition, I expect you to check slack daily for announcements and updates. This means looking in the channel for the current semester as well as any project channels that you are on.

You do not need to post regularly in the slack, but before you reach out to me with a general programming question or debugging issue, I do expect you to put your question in the slack first, to see if anyone else can answer it. Your peers will learn from helping you, and you will learn from returning the favor.

### Project note taking policy

There are two types of notes I expect you to keep updated:

1. When you join the group, you will get a personal “lab notebook” on Google drive. This does not need to be formatted in any specific way - it’s just a place for you to keep track of what you were doing, any useful tips you want to remember, and troubleshooting issues that arise. You are free to decide what workflow works best for you.
2. When you are added to a project, you will also be added to that project’s documentation in overleaf. Any time you make a significant change or discover a noteworthy insight about that project, I expect you to add it to the project’s documentation.

## Senior Thesis

### Time expectations

You should consider your thesis project as equivalent to a demanding upper-level course. The minimum amount of work, including “in-class” time (e.g. our weekly meetings or one-on-one meetings), for a 1.0 credit course is 12 hours per week. Given that this is your culminating project for your Physics major at Bates, that means you should expect to devote more like 15 hours per week towards your thesis project.

### Mid-semester check-in

Sometime in the middle of the semester, the department will schedule a thesis progress presentation time. One week prior to the thesis progress presentation, you will do the following:

1. Turn in a draft of a 7-minute talk on the work you have done so far this semester and the remaining work to do
2. [Schedule a 30 minute meeting with me](https://calendly.com/caseyberger/research-meeting) to talk through your presentation slides

During the weekly group meeting that falls before to the thesis progress presentations, we will devote the whole time to practicing talks and giving each other feedback.

### Final drafts (and progress reports for two-semester theses)

At the end of the semester, you will turn in a final draft of your thesis. One week prior to the department’s final deadline, I will ask you to send me a draft of your thesis so I can provide feedback.

If you are doing a two-semester thesis or an honors thesis, I will ask you to submit a progress report at this time. Think of this as a chance to get way ahead on your thesis drafting — draft as much as you can given the work you have done so far, add 1-2 pages at the end on your remaining project goals, your schedule for completing those goals, and any support you could use in the winter term and submit that to me by the end of the fall semester. 

## Honors Thesis

If you are planning to do an honors thesis, here is how that will work. 

- First, we will commit to a two-semester thesis, with the intention to convert to an honors thesis in the winter term
- In the first week of the fall semester, we will meet and discuss your project. Your first task will be to convert what we discussed in our meeting into a brief (2-page) thesis proposal, which must include a literature review with at least 5 sources. This will be due one week after our meeting.
- You will work the expected hours on your thesis, completing all the same requirements as a regular thesis project, during the fall semester.
- At the end of the fall semester, we will meet and discuss your work and whether you are still on-track to complete an honors-level thesis.
- If the department agrees that you are on track for an honors thesis, in the winter term, per the college’s [honors thesis calendar](https://www.bates.edu/honors/calendar/), the department will nominate you to the college for an honors thesis, and you will progress with the schedule set out by the college.