---
title: "Old Content to maybe delete"
format: 
  html:
    link-external-newwindow: true
    html-math-method: webtex
editor: source
---






## C++ asin and acos <a id='QL_trig_comp'></a>

<div class="alert alert-warning">Add a few figures here and discuss the differences in domain for asin and acos in C++ -- also why might it be that even after converting the results of acos to match those of asin, some of them are so wrong?? Are these the cases that occur along the asymptote of asin?
</div>


## Monte Carlo with Analytical Continuation

### Markov Chain Monte Carlo

<div class="alert alert-warning">Fill in with the algorithm for MCMC on this system.
    
Discuss the way the lattice is updated, including exceptional configs? You can link to the later discussion of that.
</div>

### Calculating observables

<div class="alert alert-warning">Fill in -- discuss which observables we calculate, which configs we output, and why.
</div>

### Analytic continuation

The simulation is run for imaginary values of $\theta$, which means we must analytically continue our results for real $\theta$. To do this, we fit our results to a curve and then substitute our imaginary $i \theta = \nu$ for a real $\theta = -i \nu$.

### Testing and Troubleshooting

#### Optimization and parallelization

<div class="alert alert-warning">Add a speedup plot here to show your parallelization results.
</div>



### Systematics

<div class="alert alert-warning">Fill in with plots of systematic tests. To include:
    
Determining thermalization
    
Accounting for autocorrelation
    
Error calculation

Extrapolating to continuum/thermodynamic limits?
</div>

### Results

## Complex Langevin Approach

Another approach to systems with a sign problem is to use Complex Langevin. This has been demonstrated to be successful across disciplines and systems.
<div class="alert alert-warning"> Cite at least 6 papers -- condensed matter, HEP, QCD </div>

The complex Langevin method, like all methods that tackle the sign problem, has challenges as well as benefits (see [Berger et al, 2021](https://www.sciencedirect.com/science/article/pii/S0370157320303422)) <div class="alert alert-warning"> Cite more? E.g. "The complex langevin method: when can it be trusted?" </div> 

It can sometimes converge to mathematically correct but physically invalid solutions (see [Guralnik and Pehlevan, 2008](https://arxiv.org/abs/0710.3756)). It can sometimes diverge due to numerical instabilities, which can be controlled at the cost of computational time <div class="alert alert-warning"> Pick a few of the relevant citations here </div>


```python

```